### ISSUE TITLE
Plugin name has a typo

### ISSUE THREAD

**Issue by MicrocontrollersDev** [MarkChan0225/RoundedDiscord-RePlugged#1]
Looking at [manifest.json](https://github.com/MarkChan0225/RoundedDiscord-RePlugged/blob/main/manifest.json), the package ids, name, and github source link all say RounedDiscord instead of RoundedDiscord (missing the 'd').

**Comment by MarkChan0225** [comment]
Bruh, this can't be fixed on the replugged store. I should not copy and paste these.
